version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    hostname: redis
    networks:
      - redis-net
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  redis-data:

networks:
  redis-net:
